# NOTE: Swagger also works with JSON!

openapi: 3.0.0
info:
  title: REST API with MEN
  # Things won't be cool if I want to write a meaty, multiline description:
  # https://stackoverflow.com/a/21699210
  description: "This is a student API made for a course.
    Contains the basics - CRUD operations for minimal registered and guest users.\n
    Content domain: Products (TODO: replace with something else)"
  version: 1.0.0-tutorial
servers:
  - url: http://localhost:4000/api/
    description: Localhost development server

tags:
  - name: GET Routes
    description: Routes that return information from the database. Not protected.
  - name: POST Routes
    description: Routes that add to the database. Create a user and authenticate to use these.
    # And in reality, this ONLY pairs names with descriptions. We may use tags not "defined" here just fine.

components:
  securitySchemes:  # this is what appears as a popup once you click "Authorize" in Swagger
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: auth-token

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        inStock:
          type: boolean
    
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        date:
          type: string

paths:

  /user/register:
    post:
      summary: Register a new User
      description: Register a new User in the database
      tags:
        - POST Routes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: User created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string

  /user/login:
    post:
      summary: Login a User
      description: Login a User in order to get JWT token (auth-token)
      tags:
        - POST Routes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      
      responses:
        200:
          description: User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string


  /products:
    get:
      tags:
        - GET Routes
      summary: Retrieves a list of Products
      description: Retrieves a list of products as JSON objects.
      responses:
        200:
          description: A list of product JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"  # the ref is to the "components" object defined within THIS file
        500:
        # 5XX:
          description: Unexpected server error.
    
    post:
      summary: Create a new Product
      description: Create a new Product
      security:
        - ApiKeyAuth: []      
      tags:
        - POST Routes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

      responses:
        201:
          description: Product created succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        401:
          description: "Unauthorized user tried to create a Product without passing a token.
            (Pass a response JWT token with this request.)"
        400:
          description: "Unauthorized user tried to create a Product with an invalid token.
            (Try again - either wrongly copypasted from the response, or a bad malicious attempt.)"
  
  /products/{id}:
    get:
      tags:
        - GET Routes
      summary: Specific Product
      description: Retrieves a specific Product based on it id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A Product in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
   
    put:
      summary: Updates a specific Product
      description: Updates a specific Product based on it id
      security:
        - ApiKeyAuth: []            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

      responses:
        201:
          description: Product updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

    delete:
      summary: Deletes a specific Product
      description: Deletes a specific Product based on it id
      security:
        - ApiKeyAuth: []            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string      

      responses:
        201:
          description: Product deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"